### ISSUE TITLE
文档错误 r-link

### ISSUE THREAD

**Issue by Qquanwei** [regularjs/regular-state#7]
![image](https://user-images.githubusercontent.com/9263655/52939672-bd48eb00-339f-11e9-9827-af14ab6c5b2d.png)

```html
<a href="app.a.b.c">配置</a>
<a r-link="app.a.b.c">配置</a>
<a r-link href="app.a.b.c">配置</a>

```
按照文档内容依然不知道具体r-link怎么用的。上面三种写法均未生效.

**Comment by leeluolee** [comment]
```js
r-link='app.a.b.c()'
```
@Qquanwei 

不过文档确实描述上，理解会有困难，我改下

**Comment by Qquanwei** [comment]
是的，这样可以了。
